### ISSUE TITLE
[Fixed - See edit] Can't translate strings using esc_html_x

### ISSUE THREAD

**Issue by jreklund** [wpbakery/visual-composer-starter#166] opened 2017-11-28 14:48 UTC
Hi, I'm trying to translate the following strings. But they never seem to update.

template-tags.php (3 hits)
```
Line 191: <?php echo esc_html_x( 'On', 'Post meta', 'visual-composer-starter' ); ?>
Line 195: <?php echo esc_html_x( 'by', 'Post meta', 'visual-composer-starter' ); ?>
Line 199: <?php echo esc_html_x( 'to', 'Post meta', 'visual-composer-starter' ); ?>
```
searchform.php (2 hits)
```
Line 13: <span class="screen-reader-text"><?php echo esc_html_x( 'Search for:', 'label', 'visual-composer-starter' ); ?></span>
Line 16: <button type="submit" class="search-submit"><span class="screen-reader-text"><?php echo esc_html_x( 'Search', 'submit button', 'visual-composer-starter' ); ?></span></button>
```
Replacing them with esc_html__ works. But I can't seem to find how to reference "Post meta", "label" or "submit button" on these strings. I guess you used esc_html_x due to the fact that "On" are quite generic, but how does that function even work?

```
<?php echo esc_html__( 'On', 'visual-composer-starter' ); ?>
```
Here's my files:
[languages.zip](https://github.com/wpbakery/visual-composer-starter/files/1510322/languages.zip)

EDIT: Finally found a website that reference this:
http://wpengineer.com/2237/whats-the-difference-between-__-_e-_x-and-_ex/

You will need to update the .pot file to include `msgctxt "Post meta"`. This works now.
```
#: inc/template-tags.php:191
msgctxt "Post meta"
msgid "On"
msgstr "Skrivit den"

#: inc/template-tags.php:195
msgctxt "Post meta"
msgid "by"
msgstr "av"

#: inc/template-tags.php:199
msgctxt "Post meta"
msgid "to"
msgstr "i"

#: searchform.php:13
msgctxt "label"
msgid "Search for:"
msgstr "Sök efter:"

#: searchform.php:16
msgctxt "submit button"
msgid "Search"
msgstr "Sök"
```

And this one are missing completely:
```
#: searchform.php:14
msgctxt "placeholder"
msgid "Search &hellip;"
msgstr "Sök &hellip;"
```

Can make a pull request later for this, if you want. Don't have git on this computer.

**Comment by veidenbaums** [comment] 2018-07-31 11:46
Duplicate of #209 , it should be fixed by now, added missed esc_attr_x and esc_html_x

**Closed by veidenbaums** 2018-07-31 11:46 UTC
